name: Our CI

on:
    pull_request:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
    test:
        name: Run tests
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ["3.8", "3.12"]
                include:
                    - os: macos-14
                      python-version: "3.9"
        runs-on: ${{ matrix.os }}
        steps:
            - id: step1
              run: echo "myvar=42" >> $GITHUB_OUTPUT
            - run: echo $myvar
            - run: echo "$myvar = ${{ steps.step1.outputs.myvar }}"
            - uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - if: runner.os == 'Linux'
              run: echo This is Linux
            - run: echo This is ${{ runner.os }}
            - run: python -m pip install .[test]
            - name: Run tests
              run: python -m pytest

    deploy:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        needs: test
        steps:
            - run: echo Deploy job

